site_name: Agipix Documentation
site_description: Open-source indoor autonomous aerial robotics platform - simulation and hardware with full autonomy stack in ROS2
site_author: Sasanka Kuruppu Arachchige
site_url: https://sasakuruppuarachchi.github.io/agipix/
repo_name: SasaKuruppuarachchi/agipix
repo_url: https://github.com/SasaKuruppuarachchi/agipix
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/exploded.gif
  favicon: assets/images/real.jpg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SasaKuruppuarachchi/agipix
    - icon: fontawesome/solid/envelope
      link: mailto:sasa.kuruppuarachchi@gmail.com

copyright: Copyright &copy; 2025 Sasanka Kuruppu Arachchige - Supported by RAICAM, MSCA HORIZON EU

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quick-start.md
  - Simulation:
    - Setup: simulation/setup.md
  - Hardware:
    - Assembly: hardware/assembly.md
    - Flashing Firmware: hardware/flashing.md
    - Software Setup: hardware/software-setup.md
  - Autonomy Stack:
    - Overview: autonomy/overview.md
  - Bill of Materials:
    - BOM: bom/bom.md
  - About:
    - License: about/license.md
    - Citation: about/citation.md
    - Contact: about/contact.md
